version : '1.0'

services:
  postgres:
    image: postgres
    ports :
     - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=123456
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile : Docker/dockerfile.backend
    ports:
      - '3001:3001'
    environment:
      - DATABASE_URL=postgresql://postgres:123456@postgres:5432/table
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile : Docker/dockerfile.frontend
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:123456@postgres:5432/table
    depends_on:
      - postgres

  ws:
     build:
      context: .
      dockerfile : Docker/dockerfile.socket
     ports:
      - '8080:8080'
     environment:
      - DATABASE_URL=postgresql://postgres:123456@postgres:5432/table
     depends_on:
      - postgres
    
volumes:
  postgres_data:

