FROM node:20-alpine

WORKDIR /app

COPY ./package.json ./package.json
COPY ./packages ./packages
COPY ./package-lock.json ./package-lock.json
COPY ./turbo.json ./turbo.json
COPY ./apps/http-server ./apps/http-server

RUN npm install
RUN npm run db:migrate 

EXPOSE 3001

CMD ["npm","run","start-http"]

