FROM node:20-alpine

WORKDIR /app

COPY ./packages.json ./packages.json
COPY ./packages ./packages
COPY ./package-lock.json ./package-lock.json
COPY ./apps/http-server ./apps/http-server

RUN npm install
RUN npm run db:migrate 

COPY . . 

EXPOSE 3001

CMD ["npx","tsx","index.ts"]

